version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.17.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/mmaddox93/Vatsim-Live/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  deployment:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm start 

workflows:
  my-custom-workflow:
    jobs:
      - deployment