version: 2.1
orbs:
 node: circleci/node@5.0.0
 github-cli: circleci/github-cli@2.0.0
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.17.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/mmaddox93/Vatsim-Live/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  deployment:
 
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
         npm install vue
         
workflows:
  my-custom-workflow:
    jobs:
      - deployment