version: '2.1'
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  Orb tools:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - heroku/install
workflows:
  example-workflow:
    jobs:
      - Orb tools
     

